# Generated by Django 2.0 on 2018-11-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181106_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lit',
            new_name='Litige',
        ),
    ]
