# Generated by Django 2.0 on 2018-11-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181106_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litige',
            old_name='entreprise',
            new_name='entreprises_impactés',
        ),
    ]
