# Generated by Django 2.0 on 2018-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181106_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litige',
            name='entreprises_impactés',
            field=models.CharField(default='', max_length=40),
        ),
    ]
