# Generated by Django 2.0 on 2018-11-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181106_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litige',
            name='fai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
