# Generated by Django 2.0 on 2018-11-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181106_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litige',
            old_name='entreprises_impactés',
            new_name='entreprises_impactées',
        ),
    ]
