# Generated by Django 2.0 on 2018-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181108_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['id_client'],
            },
        ),
    ]
