# Generated by Django 2.0 on 2018-11-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litige',
            name='fai',
            field=models.ForeignKey(default='{{ user.username }}', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
